// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATfISu1sTD0COpFqeuItgruUK4-YZazc8',
    appId: '1:781970592649:web:910d7eada83ec714828758',
    messagingSenderId: '781970592649',
    projectId: 'ecoquest-183f7',
    authDomain: 'ecoquest-183f7.firebaseapp.com',
    storageBucket: 'ecoquest-183f7.firebasestorage.app',
    measurementId: 'G-C6YPZ5X3TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiQksaPgHZqE3Efs8xW7266mM3c7PX_8',
    appId: '1:781970592649:android:f508800a8352fa3f828758',
    messagingSenderId: '781970592649',
    projectId: 'ecoquest-183f7',
    storageBucket: 'ecoquest-183f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZILK-fRdfYD2C9prk_gZMG5Tn73ieS8A',
    appId: '1:781970592649:ios:fafceb04d7ad3148828758',
    messagingSenderId: '781970592649',
    projectId: 'ecoquest-183f7',
    storageBucket: 'ecoquest-183f7.firebasestorage.app',
    iosBundleId: 'com.example.ecoQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZILK-fRdfYD2C9prk_gZMG5Tn73ieS8A',
    appId: '1:781970592649:ios:fafceb04d7ad3148828758',
    messagingSenderId: '781970592649',
    projectId: 'ecoquest-183f7',
    storageBucket: 'ecoquest-183f7.firebasestorage.app',
    iosBundleId: 'com.example.ecoQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATfISu1sTD0COpFqeuItgruUK4-YZazc8',
    appId: '1:781970592649:web:fa27c72059c737c7828758',
    messagingSenderId: '781970592649',
    projectId: 'ecoquest-183f7',
    authDomain: 'ecoquest-183f7.firebaseapp.com',
    storageBucket: 'ecoquest-183f7.firebasestorage.app',
    measurementId: 'G-1GG97SMDFE',
  );
}
